In [1]:
import pandas as pd
import numpy as np

personalfinance=pd.read_csv("personal_finance_tracker_dataset.csv")
personalfinance.head()

,date,user_id,monthly_income,monthly_expense_total,savings_rate,budget_goal,financial_scenario,credit_score,debt_to_income_ratio,loan_payment,...,discretionary_spending,essential_spending,income_type,rent_or_mortgage,category,cash_flow_status,financial_advice_score,financial_stress_level,actual_savings,savings_goal_met
0,2019-01-01,1584,3119.58,3212.07,0.38,3676.11,inflation,721.0,0.56,125.77,...,857.55,1910.85,Freelance,1501.65,Investments,Positive,8.3,Low,0.00,0
1,2019-01-31,1045,3262.44,3732.81,0.10,2607.17,inflation,670.0,0.42,454.19,...,534.51,3165.20,Salary,1603.17,Investments,Positive,22.6,Low,0.00,0
2,2019-03-02,1756,2931.20,3335.58,0.15,3004.14,inflation,691.0,0.24,971.82,...,353.67,1504.56,Freelance,1097.82,Healthcare,Positive,58.8,Low,0.00,0
3,2019-04-01,1724,3506.79,2327.59,0.17,3346.97,normal,717.0,0.16,482.76,...,594.08,1450.72,Freelance,1155.64,Groceries,Positive,74.5,Low,1179.20,0
4,2019-05-01,1600,4606.87,2182.58,0.34,2670.09,inflation,795.0,0.25,263.74,...,556.86,1000.00,Salary,1170.86,Utilities,Negative,38.7,High,2424.29,0

In [3]:
personalfinance.isnull().sum()

date                      0
user_id                   0
monthly_income            0
monthly_expense_total     0
savings_rate              0
budget_goal               0
financial_scenario        0
credit_score              0
debt_to_income_ratio      0
loan_payment              0
investment_amount         0
subscription_services     0
emergency_fund            0
transaction_count         0
fraud_flag                0
discretionary_spending    0
essential_spending        0
income_type               0
rent_or_mortgage          0
category                  0
cash_flow_status          0
financial_advice_score    0
financial_stress_level    0
actual_savings            0
savings_goal_met          0
dtype: int64

In [4]:
personalfinance.head()

,date,user_id,monthly_income,monthly_expense_total,savings_rate,budget_goal,financial_scenario,credit_score,debt_to_income_ratio,loan_payment,...,discretionary_spending,essential_spending,income_type,rent_or_mortgage,category,cash_flow_status,financial_advice_score,financial_stress_level,actual_savings,savings_goal_met
0,2019-01-01,1584,3119.58,3212.07,0.38,3676.11,inflation,721.0,0.56,125.77,...,857.55,1910.85,Freelance,1501.65,Investments,Positive,8.3,Low,0.00,0
1,2019-01-31,1045,3262.44,3732.81,0.10,2607.17,inflation,670.0,0.42,454.19,...,534.51,3165.20,Salary,1603.17,Investments,Positive,22.6,Low,0.00,0
2,2019-03-02,1756,2931.20,3335.58,0.15,3004.14,inflation,691.0,0.24,971.82,...,353.67,1504.56,Freelance,1097.82,Healthcare,Positive,58.8,Low,0.00,0
3,2019-04-01,1724,3506.79,2327.59,0.17,3346.97,normal,717.0,0.16,482.76,...,594.08,1450.72,Freelance,1155.64,Groceries,Positive,74.5,Low,1179.20,0
4,2019-05-01,1600,4606.87,2182.58,0.34,2670.09,inflation,795.0,0.25,263.74,...,556.86,1000.00,Salary,1170.86,Utilities,Negative,38.7,High,2424.29,0

In [5]:
new_columns = ['monthly_income', 'monthly_expense_total', 'savings_rate','budget_goal','credit_score','debt_to_income_ratio','loan_payment','discretionary_spending','essential_spending','rent_or_mortgage', 'financial_advice_score', 'financial_stress_level','actual_savings']
personalfinance=personalfinance.drop([c for c in personalfinance.columns if c not in new_columns],axis=1)
personalfinance.head()

,monthly_income,monthly_expense_total,savings_rate,budget_goal,credit_score,debt_to_income_ratio,loan_payment,discretionary_spending,essential_spending,rent_or_mortgage,financial_advice_score,financial_stress_level,actual_savings
0,3119.58,3212.07,0.38,3676.11,721.0,0.56,125.77,857.55,1910.85,1501.65,8.3,Low,0.00
1,3262.44,3732.81,0.10,2607.17,670.0,0.42,454.19,534.51,3165.20,1603.17,22.6,Low,0.00
2,2931.20,3335.58,0.15,3004.14,691.0,0.24,971.82,353.67,1504.56,1097.82,58.8,Low,0.00
3,3506.79,2327.59,0.17,3346.97,717.0,0.16,482.76,594.08,1450.72,1155.64,74.5,Low,1179.20
4,4606.87,2182.58,0.34,2670.09,795.0,0.25,263.74,556.86,1000.00,1170.86,38.7,High,2424.29

In [6]:
import os
data=personalfinance
df=pd.DataFrame(data)
csv_filename="cleaned_personalfinance.csv"
df.to_csv(csv_filename, index=False)
print(f"Success! '{csv_filename}' has been created in: {os.getcwd()}")

Success! 'cleaned_personalfinance.csv' has been created in: c:\Users\MSI\Downloads\ML-For-Beginners-main (1)\Capstone\FinTwin-ai\Uncleaned Data