In [2]:
import pandas as pd
import numpy as np

personalexpense=pd.read_csv("personal_expense_dataset.csv")
personalexpense.head()

       Date       Category  Amount Payment_Mode     Month
0  1/1/2024      Transport    3279         Cash       May
1  1/2/2024  Entertainment    2080         Card  December
2  1/2/2024      Transport    3217       Online  December
3  1/2/2024      Utilities    1054       Online       May
4  1/5/2024           Food   13249         Cash  December

In [3]:
personalexpense.isnull().sum()

Date            0
Category        0
Amount          0
Payment_Mode    0
Month           0
dtype: int64

In [4]:
new_columns=['Category','Amount','Month']
personalexpense=personalexpense.drop([c for c in personalexpense.columns if c not in new_columns],axis=1)
personalexpense.head()

        Category  Amount     Month
0      Transport    3279       May
1  Entertainment    2080  December
2      Transport    3217  December
3      Utilities    1054       May
4           Food   13249  December

In [5]:
import os
data=personalexpense
df=pd.DataFrame(data)
csv_filename="cleaned_personalexpense.csv"
df.to_csv(csv_filename, index=False)
print(f"Success! '{csv_filename}' has been created in: {os.getcwd()}")

Success! 'cleaned_personalexpense.csv' has been created in: c:\Users\MSI\Downloads\ML-For-Beginners-main (1)\Capstone\FinTwin-ai\Uncleaned Data